trigger:

- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'curl -sSL https://download.sourceclear.com/ci.sh | sh'
  env: 
    SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN)

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Veracode@2
  inputs:
    AnalysisService: 'vera_azure'
    veracodeAppProfile: 'VeraInsecure'
    version: '$(build.buildNumber)'
    filepath: '/home/vsts/work/1/s/target/verainsecure.war'
    sandboxName: 'AzureDevOps'
