# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

 - task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      unzip pipeline-scan-LATEST.zip -d pipeline-scan-LATEST
      java -jar "pipeline-scan-LATEST/pipeline-scan.jar" -vid $(veracode_id) -vkey $(veracode_key) --fail_on_severity "Very High" -f "target/verainsecure.war"
- task: Veracode@2
  inputs:
    AnalysisService: 'vera_azure'
    veracodeAppProfile: 'VeraInsecure 2021'
    version: '$(build.buildNumber)'
    filepath: '/home/vsts/work/1/s/target/verainsecure.war'
    sandboxName: 'AzureDevOps'   

