trigger:

- master

pool:
  vmImage: 'windows-2019'

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

# - task: Veracode@3
#   inputs:
#     ConnectionDetailsSelection: 'Credentials'
#     apiId: '- task: CmdLine@2
  inputs:
    script: |
      curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
              unzip -o pipeline-scan-LATEST.zip
              java -jar pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f $(build.artifactstagingdirectory)\VeraInsecure.zip || true'
#     apiKey: '6fc0608c4fc610ff2cb8557fb5c47240e1787544f87b684f369145c3ba05ae79f68428bad1fb9bc59ff70be457ee6b80f96adede7c82515f5612b653a47b254d'
#     veracodeAppProfile: '$(system.teamProject)'
#     version: '$(build.buildNumber)'
#     filepath: '$(build.artifactstagingdirectory)'
#     createProfile: true
#     maximumWaitTime: '360'

# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       $Env:SRCCLR_API_TOKEN
#       Set-ExecutionPolicy AllSigned -Scope Process -Force
#       iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
#       srcclr scan


