trigger:

- master

pool:
  vmImage: 'windows-2019'

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '8902e24c2f234d2a4845c58f7ae1bd83'
    apiKey: '2cf8130a75d06adaf312a39179640036bdff5b3f0c258cb51c8109624d2b93883cd49319e5ecf25a0d0e415afde61f410b9b593f73067743d7441ee81ca483f4'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    createProfile: true
    maximumWaitTime: '360'