# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Veracode Security Checks

on: [pull_request]

jobs:
  buildVeracodeBaseline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Pipeline Scan
      run: |
        curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip pipeline-scan-LATEST.zip -d pipeline-scan-LATEST
        java -jar pipeline-scan-LATEST/pipeline-scan.jar -vid ${{ secrets.veracode_id }} -vkey ${{ secrets.veracode_key }} -f 'target/verainsecure.war' --fail_on_serverity 'Very High' --json_output_file="baseline.json"
    - name: Upload Baseline
      uses: actions/upload-artifact@v1
      with:
        name: baseline
        path: baseline.json
 
  veracodeChecks:
    runs-on: ubuntu-latest
    needs: buildVeracodeBaseline
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: download baseline
      uses: actions/download-artifact@v1
      with:
        name: baseline
    - name: Pipeline Scan
      run: |
        curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip pipeline-scan-LATEST.zip -d pipeline-scan-LATEST
        java -jar pipeline-scan-LATEST/pipeline-scan.jar -vid ${{ secrets.veracode_id }} -vkey ${{ secrets.veracode_key }} -f 'target/verainsecure.war' --baseline_file "baseline/baseline.json"
